### PR TITLE
Templates in templates

### PR DESCRIPTION
**Pull request by kylepaulsen**
Add recursiveRender option to allow templates to have templates.

I know this is kind of a crazy change, but I'd thought I'd share it with you in case you'd allow it. I feel like this feature really gives me a lot of power for very little set up (see the test case). Feel free to change whatever or ask me to change things.

Thanks anyway for the code.

### CODE REVIEW

**Comment by wbyoung** [comment]
After using a few other static site generators, this is something that I was expecting would work out of the box.

I don't think that the ability to have this work with engines like Handlebars is the only advantage here. I've switched to SWIG for the project I'm working on to get some of the functionality that's provided here, but being able to define new variables within the front-matter of templates would allow solutions that (as far as I can tell) aren't possible by just using SWIG as it doesn't have something similar to a [`with`](https://docs.djangoproject.com/en/1.7/ref/templates/builtins/#with) template.

Coupled with the ability to support recursive template building with any template engine, I think this is a must-have feature for `metalsmith-templates`.

Obviously, @kylepaulsen is not alone in wanting this to happen. #27 and #21 are requesting similar functionality. This PR seems to me like it's heading down the right track & addresses the issues from both of those PRs. It feels very natural & is very similar to the way that Jekyll handles templates. It's the way that I assumed things would work.

**Comment by joakim** [comment]
I agree with what's being said here, and hope this PR will get some love :+1:

**Comment by ismay** [comment]
@joakim Something like this can also be done with https://github.com/shannonmoeller/handlebars-layouts, see https://github.com/ismay/ismaywolff.nl/blob/master/src/index.hbs for an example. Works flawlessly.

**Comment by ianstormtaylor** [comment]
Hey thanks for this sorry for the delay. Now that https://github.com/superwolff has split out this plugin into two separate plugins—[layouts](https://github.com/superwolff/metalsmith-layouts) and [in-place](https://github.com/superwolff/metalsmith-in-place)—I'm going to deprecate the `metalsmith-templates` plugin, so that we can use the simpler ones instead. I'm going to close this PR, but feel free to re-open there!

Added a deprecation notice to the [readme](https://github.com/segmentio/metalsmith-templates/blob/master/Readme.md).

(I think the idea of recursive layouts is genius btw. Very elegant.)

**Pull request closed without merging**
