### PR TITLE
Deep clone params because consolidate stomps the partials

### PR DESCRIPTION
**Pull request by mpd106**
Using metalsmith-templates + handlebars (haven't tested other engines) + metalsmith-watch results in an error on the second processing of a partial (triggered by modifying content that depends on that partial). It looks as though consolidate stomps on the `partials` object in one of its arguments, which means on the second compilation it'll try to find a file whose name is the _contents_ of that partial, rather than the name.

Fix is to simply deep clone the `params`.

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
I think we might want to be only deep cloning the `params` and not the other two objects if we don't have to? Curious to know what the performance loss is on the deep clone is all

**Comment by mpd106** [comment]
You're right re: deep clone--I've made the corresponding change. As for perf, as a quick test I ran it on a site with 1k pages and 10 partials and the performance difference with the additional deep clone wasn't statistically significant.

I've also added a corresponding test--should have done in the first place but was in a hurry :)

**Comment by ianstormtaylor** [comment]
awesome thanks!

**Comment by benpolinsky** [comment]
Hi,

I've got a nested each loop in handlebars, iterating over all collections, and then through each collection to display a table of contents - simple stuff.

However, I'm getting duplicate collection items on the _second reload_  if my table of contents partial changes. I'm wondering if this could be related to this PR.  I can try to investigate more later.

**Pull request merged**
